import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <div className='navigation'>
        <a className='nav-link' href="/">
          Home
        </a>
        <a className='nav-link' href="/about">
          About
        </a>
      </div>
      <main>{children}</main>
      </body>
    </html>
  )
}
